package com.yjl.mybatis.entity;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customer_id
     *
     * @mbggenerated Fri Sep 24 21:36:50 CST 2021
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customer_name
     *
     * @mbggenerated Fri Sep 24 21:36:50 CST 2021
     */
    private String customerName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customer_id
     *
     * @return the value of tb_customer.customer_id
     *
     * @mbggenerated Fri Sep 24 21:36:50 CST 2021
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customer_id
     *
     * @param customerId the value for tb_customer.customer_id
     *
     * @mbggenerated Fri Sep 24 21:36:50 CST 2021
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customer_name
     *
     * @return the value of tb_customer.customer_name
     *
     * @mbggenerated Fri Sep 24 21:36:50 CST 2021
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customer_name
     *
     * @param customerName the value for tb_customer.customer_name
     *
     * @mbggenerated Fri Sep 24 21:36:50 CST 2021
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }
}